'\" t
.\"     Title: mkvimball-sh
.\"    Author: Lawrence Velazquez
.\" Generator: Asciidoctor 2.0.17
.\"      Date: 2022-03-10
.\"    Manual: mkvimball-sh Manual
.\"    Source: mkvimball-sh 0.1
.\"  Language: English
.\"
.TH "MKVIMBALL\-SH" "1" "2022-03-10" "mkvimball\-sh 0.1" "mkvimball\-sh Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
mkvimball-sh, mkvimball \- create a vimball archive
.SH "SYNOPSIS"
.sp
\fBmkvimball\-sh\fP [\fB\-a\fP] [\fB\-f\fP \fIarchive\fP] [\-\-] [\fIfile\fP ...]
.br
\fBmkvimball\fP \fIarchivebase\fP \fIfile\fP ...
.SH "DESCRIPTION"
.sp
The \fBmkvimball\-sh\fP utility copies the contents of the files named by the
\fIfile\fP operands to a vimball archive.  The archive is written to
standard output unless the \fB\-f\fP option is specified, in which case it is
written to \fIarchive\fP.  If no \fIfile\fP operands are specified, a list of
LF\-terminated pathnames is read from standard input, and the contents of
the listed files are copied to the archive.
.sp
If installed, the \fBmkvimball\fP shim provides drop\-in compatibility with
Charles E. Campbell\(cqs original \fBmkvimball\fP.
It rejects \fIarchivebase\fP if it contains a "." character; otherwise, it
writes the archive to
\fIarchivebase\fP.\fIvba\fP.
(See COMPATIBILITY for details.)
.sp
Within this document, "the utilities" refers to both \fBmkvimball\-sh\fP and
the \fBmkvimball\fP shim.
.SH "OPTIONS"
.sp
\fBmkvimball\-sh\fP endeavors to conform to the
IEEE Std 1003.1\-2017 (POSIX.1\-2017) Utility Syntax Guidelines.
In particular, the first "\-\-" argument that is not an option\-argument
marks the end of options.
.sp
The following options are supported by \fBmkvimball\-sh\fP:
.sp
\fB\-a\fP
.RS 4
Omit the archive header from the output so it can be appended to an
existing vimball archive.
.RE
.sp
\fB\-f\fP \fIarchive\fP
.RS 4
Write the vimball archive to \fIarchive\fP instead of standard output.  If
a file exists at \fIarchive\fP, it is overwritten unless \fB\-a\fP is specified,
in which case it is appended to.  If \fIarchive\fP is "\-", it refers not to
standard output but to a file named
\fI\-\fP;
this behavior may change in a future version of \fBmkvimball\-sh\fP.
.RE
.sp
The \fBmkvimball\fP shim does not recognize the "\-\-" delimiter or any
options.
.SH "OPERANDS"
.sp
The following operands are supported by \fBmkvimball\-sh\fP:
.sp
\fIfile\fP
.RS 4
A pathname of a file to be copied into the vimball archive.  The value
of the operand itself is also included in the archive.  If a \fIfile\fP
operand is "\-", it refers not to standard input but to a file named
\fI\-\fP.
.sp
If no \fIfile\fP operands are specified, pathnames are read from standard
input as described in STDIN.
.RE
.sp
The following operands are supported by the \fBmkvimball\fP shim:
.sp
\fIarchivebase\fP
.RS 4
A partial pathname used to determine where to write the vimball archive.
.sp
If the \fIarchivebase\fP operand contains a "." character, \fBmkvimball\fP
writes a diagnostic message to standard error and exits with a nonzero
status.  (See COMPATIBILITY.)
.sp
Otherwise, the archive is written to the pathname formed by
concatenating \fIarchivebase\fP and ".vba".  If a file exists there, it is
overwritten.  If the \fIarchivebase\fP operand is "\-", it refers not to
standard output but to a file named
\fI\-.vba\fP.
.RE
.sp
\fIfile\fP
.RS 4
Same as for \fBmkvimball\-sh\fP, except that one or more \fIfile\fP operands must
be specified.
.RE
.SH "STDIN"
.sp
If no \fIfile\fP operands are specified, \fBmkvimball\-sh\fP reads LF\-terminated
pathnames from standard input and uses each pathname as if it had been
a \fIfile\fP operand.  The terminating LF is optional for the final
pathname.
.sp
The \fBmkvimball\fP shim does not use the standard input, although this may
change in a future version.
.SH "INPUT FILES"
.sp
The files specified using \fIfile\fP operands or standard input must be
text files as defined by IEEE Std 1003.1\-2017 (POSIX.1\-2017).
.SH "ENVIRONMENT VARIABLES"
.sp
The \fILANG\fP, \fILC_ALL\fP, \fILC_CTYPE\fP, \fILC_MESSAGES\fP, \fINLSPATH\fP, and \fIPATH\fP
environment variables affect the execution of the utilities and their
child processes in the usual manner.
.SH "ASYNCHRONOUS EVENTS"
.sp
The standard action is taken for all signals.
.SH "STDOUT"
.sp
If \fB\-f\fP is not specified, \fBmkvimball\-sh\fP writes the vimball archive to
standard output.
.sp
The \fBmkvimball\fP shim does not use standard output.
.SH "STDERR"
.sp
The standard error is used only for diagnostic messages.
.SH "OUTPUT FILES"
.sp
If \fB\-f\fP is specified, the output file of \fBmkvimball\-sh\fP is a vimball
archive unless \fB\-a\fP is also specified and \fIarchive\fP exists but is not
a vimball archive.
.sp
The output file of the \fBmkvimball\fP shim is a vimball archive.
.SH "EXIT STATUS"
.sp
The following exit values are returned:
.sp
0
.RS 4
The vimball archive was created successfully.
.RE
.sp
>0
.RS 4
An error occurred.
.RE
.SH "CONSEQUENCES OF ERRORS"
.sp
If the utilities encounter an error, they exit with a nonzero status and
do not process any further input files.  A partial vimball archive may
be produced.
.SH "APPLICATION USAGE"
.sp
The modern, preferred suffix for vimball archive pathnames is ".vmb".
Unless compatibility is a concern, applications should avoid giving
archives the legacy ".vba" suffix.
.sp
The pathnames of input files \(em whether specified as \fIfile\fP operands or
read from standard input \(em are embedded in the output archive and are
used for constructing destination pathnames during extraction.  Thus,
the utilities must be invoked from a directory that permits passing the
proper pathnames.  For example, given this directory structure...
.sp
.if n .RS 4
.nf
.fam C
/home
`\-\- dave
    `\-\- src
        `\-\- ex1
            |\-\- autoload
            |   `\-\- ex1.vim
            |\-\- doc
            |   `\-\- ex1.txt
            `\-\- plugin
                `\-\- ex1.vim
.fam
.fi
.if n .RE
.sp
\&...the
\fIex1\fP
plugin could be packaged using the following Bourne shell command:
.sp
.if n .RS 4
.nf
.fam C
cd /home/dave/src/ex1 \(rs
    && mkvimball\-sh ex1.vmb \(rs
        autoload/ex1.vim doc/ex1.txt plugin/ex1.vim
.fam
.fi
.if n .RE
.sp
The utilities produce invalid vimball archives if given input files that
do not end with a LF character (ASCII 10\~/ 0x0A\~/ 0o12) or
that terminate lines with CR (ASCII 13\~/ 0x0D\~/ 0o15) or CRLF.
Applications must convert such files to compliant text files (see
INPUT FILES) before using them with the utilities; they can also be
handled with the vimball Vim plugin.
.sp
The utilities provide no facility for embedding values of the Vim
\fIfileencoding\fP
option into archives.  Applications should consider restricting input to
ASCII characters to avoid relying on Vim\(cqs encoding heuristics during
extraction.
.SH "EXAMPLES"
.sp
The following command outputs a vimball archive to standard output:
.sp
.if n .RS 4
.nf
.fam C
mkvimball\-sh autoload/ex2.vim doc/ex2.txt plugin/ex2.vim
.fam
.fi
.if n .RE
.sp
The following command creates a vimball archive named
\fIex3.vmb\fP:
.sp
.if n .RS 4
.nf
.fam C
mkvimball\-sh \-f ex3.vmb autoload/ex3.vim doc/ex3.txt plugin/ex3.vim
.fam
.fi
.if n .RE
.sp
The following command creates a vimball archive named
\fIex4.vmb\fP,
with the input pathnames read from a text file:
.sp
.if n .RS 4
.nf
.fam C
mkvimball\-sh \-f ex4.vmb <ex4_filelist
.fam
.fi
.if n .RE
.sp
The following command creates a vimball archive named
\fIex5.vba\fP
using the \fBmkvimball\fP shim:
.sp
.if n .RS 4
.nf
.fam C
mkvimball ex5 autoload/ex5.vim doc/ex5.txt plugin/ex5.vim
.fam
.fi
.if n .RE
.sp
The following command adds documentation to an existing vimball archive
named \f(CRex6.vmb\fP:
.sp
.if n .RS 4
.nf
.fam C
mkvimball\-sh \-af ex6.vmb doc/ex6.txt
.fam
.fi
.if n .RE
.SH "COMPATIBILITY"
.sp
Charles E. Campbell\(cqs original \fBmkvimball\fP
rejects archive pathnames that contain "." characters.  The \fBmkvimball\fP
shim retains this behavior, but \fBmkvimball\-sh\fP accepts such pathnames.
.sp
The original \fBmkvimball\fP appends ".vba" to those archive pathnames that
it does accept.  The \fBmkvimball\fP shim retains this behavior, but
\fBmkvimball\-sh\fP uses all operands as given.
.sp
If invoked without any input pathnames, the original \fBmkvimball\fP enters
an interactive mode that prompts the user to enter pathnames.  The
\fBmkvimball\fP shim does not provide such a mode, but \fBmkvimball\-sh\fP reads
pathnames from standard input if invoked without operands (although this
is not designed for interactive use).
.SH "BUGS"
.sp
Probably.
.SH "SEE ALSO"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The \c
.URL "https://github.com/larryv/mkvimball\-sh" "mkvimball\-sh homepage" ""
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Charles E. Campbell\(cqs \c
.URL "https://www.drchip.org/astronaut/src/index.html#MKVIMBALL" "original mkvimball" ""
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Charles E. Campbell\(cqs \c
.URL "https://www.drchip.org/astronaut/vim/index.html#VIMBALL" "Vim plugin" ""
.RE
.SH "COPYRIGHT"
.sp
To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide.  This software is distributed without any
warranty.
.sp
You should have received a copy of the CC0 Public Domain Dedication
along with this software.  If not, see
.URL "https://creativecommons.org/publicdomain/zero/1.0/" "" "."
.SH "AUTHOR"
.sp
Lawrence Velazquez