////
mkvimball-sh.adoc
-----------------

SPDX-License-Identifier: CC0-1.0

Written in 2022 by Lawrence Velázquez <vq@larryv.me>.

To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide.  This software is distributed without any
warranty.

You should have received a copy of the CC0 Public Domain Dedication
along with this software.  If not, see
<https://creativecommons.org/publicdomain/zero/1.0/>.
////


= mkvimball-sh(1)
ifdef::backend-manpage[Lawrence Velazquez]
ifndef::backend-manpage[Lawrence Velázquez]
:doctype: manpage
:manmanual: mkvimball-sh Manual
:mansource: mkvimball-sh 0.2
:source-language: sh

:orig_vimball_url: https://www.drchip.org/astronaut/vim/index.html#VIMBALL
:orig_mkvimball_url: https://www.drchip.org/astronaut/src/index.html#MKVIMBALL
:posix_title_prefix: POSIX.1-2017
:posix_url_prefix: https://pubs.opengroup.org/onlinepubs/9699919799


== Name

mkvimball-sh, mkvimball - create a vimball archive


== Synopsis

[%hardbreaks]
*mkvimball-sh* [*-a*] [*-f* _archive_] [--] [_file_ ...]
*mkvimball* _archivebase_ _file_ ...


== Description

The *mkvimball-sh* utility copies the contents of the files named by the
_file_ operands to a vimball archive.  The archive is written to
standard output unless the *-f* option is specified, in which case it is
written to _archive_.  If no _file_ operands are specified, a list of
LF-terminated pathnames is read from standard input, and the contents of
the listed files are copied to the archive.

If installed, the *mkvimball* shim provides drop-in compatibility with
ifdef::backend-manpage[]
Charles E. Campbell's original *mkvimball*.
endif::[]
ifndef::backend-manpage[]
{orig_mkvimball_url}[Charles E. Campbell's original *mkvimball*].
endif::[]
It rejects _archivebase_ if it contains a "." character; otherwise, it
writes the archive to
ifdef::backend-manpage[_archivebase_._vba_.]
ifndef::backend-manpage[`__archivebase__.vba`.]
(See <<compatibility>> for details.)

Within this document, "the utilities" refers to both *mkvimball-sh* and
the *mkvimball* shim.


== Options

*mkvimball-sh* endeavors to conform to the
ifdef::backend-manpage[]
IEEE Std 1003.1-2017 (POSIX.1-2017) Utility Syntax Guidelines.
endif::[]
ifndef::backend-manpage[]
{posix_url_prefix}/basedefs/V1_chap12.html#tag_12_02[IEEE Std 1003.1-2017 (POSIX.1-2017) Utility Syntax Guidelines,
title="{posix_title_prefix} - Volume 1, Chapter 12, Section 2"].
endif::[]
In particular, the first "--" argument that is not an option-argument
marks the end of options.

The following options are supported by *mkvimball-sh*:

*-a*::
Omit the archive header from the output so it can be appended to an
existing vimball archive.

*-f* _archive_::
Write the vimball archive to _archive_ instead of standard output.  If
a file exists at _archive_, it is overwritten unless *-a* is specified,
in which case it is appended to.  If _archive_ is "-", it refers not to
standard output but to a file named
ifdef::backend-manpage[_-_;]
ifndef::backend-manpage[`-`;]
this behavior may change in a future version of *mkvimball-sh*.

The *mkvimball* shim does not recognize the "--" delimiter or any
options.


ifndef::env-github[[#operands]]
== Operands

The following operands are supported by *mkvimball-sh*:

_file_::
A pathname of a file to be copied into the vimball archive.  The value
of the operand itself is also included in the archive.  If a _file_
operand is "-", it refers not to standard input but to a file named
ifdef::backend-manpage[_-_.]
ifndef::backend-manpage[`-`.]
+
If no _file_ operands are specified, pathnames are read from standard
input as described in <<stdin>>.

The following operands are supported by the *mkvimball* shim:

_archivebase_::
A partial pathname used to determine where to write the vimball archive.
+
If the _archivebase_ operand contains a "." character, *mkvimball*
writes a diagnostic message to standard error and exits with a nonzero
status.  (See <<compatibility>>.)
+
Otherwise, the archive is written to the pathname formed by
concatenating _archivebase_ and ".vba".  If a file exists there, it is
overwritten.  If the _archivebase_ operand is "-", it refers not to
standard output but to a file named
ifdef::backend-manpage[_-.vba_.]
ifndef::backend-manpage[`-.vba`.]

_file_::
Same as for *mkvimball-sh*, except that one or more _file_ operands must
be specified.


ifndef::env-github[[#stdin]]
== Stdin

If no _file_ operands are specified, *mkvimball-sh* reads LF-terminated
pathnames from standard input and uses each pathname as if it had been
a _file_ operand.  The terminating LF is optional for the final
pathname.

The *mkvimball* shim does not use the standard input, although this may
change in a future version.


ifndef::env-github[[#input-files]]
== Input Files

The files specified using _file_ operands or standard input must be
ifdef::backend-manpage[]
text files as defined by IEEE Std 1003.1-2017 (POSIX.1-2017).
endif::[]
ifndef::backend-manpage[]
{posix_url_prefix}/basedefs/V1_chap03.html#tag_03_403[text files as defined by IEEE Std 1003.1-2017 (POSIX.1-2017),
title="{posix_title_prefix} - Volume 1, Chapter 3, Section 403 ({quot}Text File{quot})"].
endif::[]


== Environment Variables

The _LANG_, _LC_ALL_, _LC_CTYPE_, _LC_MESSAGES_, _NLSPATH_, and _PATH_
environment variables affect the execution of the utilities and their
child processes in the usual manner.


== Asynchronous Events

The standard action is taken for all signals.


== Stdout

If *-f* is not specified, *mkvimball-sh* writes the vimball archive to
standard output.

The *mkvimball* shim does not use standard output.


== Stderr

The standard error is used only for diagnostic messages.


== Output Files

If *-f* is specified, the output file of *mkvimball-sh* is a vimball
archive unless *-a* is also specified and _archive_ exists but is not
a vimball archive.

The output file of the *mkvimball* shim is a vimball archive.


////
TODO: Write a description of the vimball format?

== Extended Description
////


== Exit Status

The following exit values are returned:

// The "horizontal" style doesn't make a difference to the manpage
// converter, so don't bother.
0:: The vimball archive was created successfully.
>0:: An error occurred.


== Consequences of Errors

If the utilities encounter an error, they exit with a nonzero status and
do not process any further input files.  A partial vimball archive may
be produced.


== Application Usage

The modern, preferred suffix for vimball archive pathnames is ".vmb".
Unless compatibility is a concern, applications should avoid giving
archives the legacy ".vba" suffix.

The pathnames of input files -- whether specified as _file_ operands or
read from standard input -- are embedded in the output archive and are
used for constructing destination pathnames during extraction.  Thus,
the utilities must be invoked from a directory that permits passing the
proper pathnames.  For example, given this directory structure...

    /home
    `-- dave
        `-- src
            `-- ex1
                |-- autoload
                |   `-- ex1.vim
                |-- doc
                |   `-- ex1.txt
                `-- plugin
                    `-- ex1.vim

...the
ifdef::backend-manpage[_ex1_]
ifndef::backend-manpage[`ex1`]
plugin could be packaged using the following Bourne shell command:

[source]
ifdef::backend-manpage[]
cd /home/dave/src/ex1 \
    && mkvimball-sh ex1.vmb \
        autoload/ex1.vim doc/ex1.txt plugin/ex1.vim
endif::[]
ifndef::backend-manpage[]
cd /home/dave/src/ex1 && mkvimball-sh ex1.vmb autoload/ex1.vim doc/ex1.txt plugin/ex1.vim
endif::[]

The utilities produce invalid vimball archives if given input files that
do not end with a LF character (ASCII 10{nbsp}/ 0x0A{nbsp}/ 0o12) or
that terminate lines with CR (ASCII 13{nbsp}/ 0x0D{nbsp}/ 0o15) or CRLF.
Applications must convert such files to compliant text files (see
<<input-files>>) before using them with the utilities; they can also be
handled with the vimball Vim plugin.

The utilities provide no facility for embedding values of the Vim
ifdef::backend-manpage[_fileencoding_]
ifndef::backend-manpage[`fileencoding`]
option into archives.  Applications should consider restricting input to
ASCII characters to avoid relying on Vim's encoding heuristics during
extraction.


== Examples

The following command outputs a vimball archive to standard output:

[source]
mkvimball-sh autoload/ex2.vim doc/ex2.txt plugin/ex2.vim

The following command creates a vimball archive named
ifdef::backend-manpage[_ex3.vmb_:]
ifndef::backend-manpage[`ex3.vmb`:]

[source]
mkvimball-sh -f ex3.vmb autoload/ex3.vim doc/ex3.txt plugin/ex3.vim

The following command creates a vimball archive named
ifdef::backend-manpage[_ex4.vmb_,]
ifndef::backend-manpage[`ex4.vmb`,]
with the input pathnames read from a text file:

[source]
mkvimball-sh -f ex4.vmb <ex4_filelist

The following command creates a vimball archive named
ifdef::backend-manpage[_ex5.vba_]
ifndef::backend-manpage[`ex5.vba`]
using the *mkvimball* shim:

[source]
mkvimball ex5 autoload/ex5.vim doc/ex5.txt plugin/ex5.vim

The following command adds documentation to an existing vimball archive
named `ex6.vmb`:

[source]
mkvimball-sh -af ex6.vmb doc/ex6.txt


ifndef::env-github[[#compatibility]]
== Compatibility

ifdef::backend-manpage[]
Charles E. Campbell's original *mkvimball*
endif::[]
ifndef::backend-manpage[]
{orig_mkvimball_url}[Charles E. Campbell's original *mkvimball*]
endif::[]
rejects archive pathnames that contain "." characters.  The *mkvimball*
shim retains this behavior, but *mkvimball-sh* accepts such pathnames.

The original *mkvimball* appends ".vba" to those archive pathnames that
it does accept.  The *mkvimball* shim retains this behavior, but
*mkvimball-sh* uses all operands as given.

If invoked without any input pathnames, the original *mkvimball* enters
an interactive mode that prompts the user to enter pathnames.  The
*mkvimball* shim does not provide such a mode, but *mkvimball-sh* reads
pathnames from standard input if invoked without operands (although this
is not designed for interactive use).


== Bugs

Probably.


== See Also

// The manpage converter already sets URL titles in bold, so including
// bold formatting fouls everything up.
ifdef::backend-manpage[]
* The https://github.com/larryv/mkvimball-sh[mkvimball-sh homepage]
* Charles E. Campbell's {orig_mkvimball_url}[original mkvimball]
* Charles E. Campbell's {orig_vimball_url}[Vim plugin]
endif::[]
ifndef::backend-manpage[]
* The https://github.com/larryv/mkvimball-sh[*mkvimball-sh* homepage]
* Charles E. Campbell's {orig_mkvimball_url}[original *mkvimball*]
* Charles E. Campbell's {orig_vimball_url}[Vim plugin]
endif::[]


== Copyright

ifndef::backend-manpage[]
Written by {author}.
endif::[]

To the extent possible under law, the author(s) have dedicated all
copyright and related and neighboring rights to this software to the
public domain worldwide.  This software is distributed without any
warranty.

You should have received a copy of the CC0 Public Domain Dedication
along with this software.  If not, see
https://creativecommons.org/publicdomain/zero/1.0/.
